# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 模型编辑器导出的代码.py
# Created on: 2019-06-09 09:29:49.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 模型编辑器导出的代码 <Kriging_经纬2> <Output_variance_of_prediction_raster> <rastercalc1> <Reclass_Krig2> <经纬点_Layer> <经纬点_csv> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module

'''
本代码为将ArcGIS modelbuilder模型直接导出的代码，除了添加本注释，未做任何更改
如果你想运行本代码，除了修改输入输出之外，好还要修改以中文名开始的变量名，python变量名不允许以中文开始
正常情况下不一定需要对model builder建的模型进行改写，本次改写的主要目的是理解ArcGIS Python二次开发
中间数据保存到一个gdb临时文件夹中
作者：太白野老
2019年6月9日
'''

import arcpy

# Script arguments
Kriging_经纬2 = arcpy.GetParameterAsText(0)
if Kriging_经纬2 == '#' or not Kriging_经纬2:
    Kriging_经纬2 = "C:\\Users\\wangxch\\Documents\\ArcGIS\\Default.gdb\\Kriging_经纬2" # provide a default value if unspecified

Output_variance_of_prediction_raster = arcpy.GetParameterAsText(1)

rastercalc1 = arcpy.GetParameterAsText(2)
if rastercalc1 == '#' or not rastercalc1:
    rastercalc1 = "C:\\Users\\wangxch\\Documents\\ArcGIS\\Default.gdb\\rastercalc1" # provide a default value if unspecified

Reclass_Krig2 = arcpy.GetParameterAsText(3)
if Reclass_Krig2 == '#' or not Reclass_Krig2:
    Reclass_Krig2 = "C:\\Users\\wangxch\\Documents\\ArcGIS\\Default.gdb\\Reclass_Krig2" # provide a default value if unspecified

经纬点_Layer = arcpy.GetParameterAsText(4)
if 经纬点_Layer == '#' or not 经纬点_Layer:
    经纬点_Layer = "经纬点_Layer" # provide a default value if unspecified

经纬点_csv = arcpy.GetParameterAsText(5)
if 经纬点_csv == '#' or not 经纬点_csv:
    经纬点_csv = "C:\\Users\\wangxch\\Desktop\\经纬点.csv" # provide a default value if unspecified

# Local variables:

# Process: Make XY Event Layer
arcpy.MakeXYEventLayer_management(经纬点_csv, "lon", "lat", 经纬点_Layer, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;.001;.001;IsHighPrecision", "")

# Process: Kriging
arcpy.gp.Kriging_sa(经纬点_Layer, "序号", Kriging_经纬2, "Spherical #", "", "VARIABLE 12", Output_variance_of_prediction_raster)

# Process: Reclassify
arcpy.gp.Reclassify_sa(Kriging_经纬2, "VALUE", "0.020690 2.094484 1;2.094484 3.797958 2;3.797958 5.427368 3;5.427368 6.686457 4;6.686457 7.649290 5;7.649290 8.538059 6;8.538059 9.426828 7;9.426828 10.537789 8;10.537789 11.870943 9;11.870943 13.426288 10;13.426288 14.907570 11;14.907570 16.611044 12;16.611044 18.981094 13", Reclass_Krig2, "DATA")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("Con(\"%Reclass_Krig2%\" == 9,100,\"%Reclass_Krig2%\")", rastercalc1)

